# Generated by Django 4.0.3 on 2023-09-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_vehicletype_make_alter_vehicletype_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='availability_status',
        ),
    ]
